### ISSUE TITLE
Breaking EULA, would suggest converting to a PR

### ISSUE THREAD

**Issue by jackknobel** [pdlogingithub/UE4-Multi-Dropping-Tool#1]
Hey there, 

These changes are really nice, however, I would suggest converting this to a [pull request](https://wiki.unrealengine.com/Git_Pull_Requests) as you are breaking the [UE4 EULA](https://www.unrealengine.com/en-US/eula) by having this much engine code publicly available. Additionally by having it as a PR it makes integrating it into users source versions of the engine a breeze.

Regardless, loving the changes, brings some much needed improvements to UE!

**Comment by pdlogingithub** [comment]
sorry,I didnt see your comment.  
I'll remove the source code,thanks for the notice,it wont happen again.

**Comment by jackknobel** [comment]
No stress! 
I don't represent Epic by any means, just trying to prevent you from getting a take-down request :)
